name: Deploy
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"

env:
  version: 0.0.${{github.run_number}}
  imageRepository: "cjoergensen/thrifty-elastic-alerting"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build image
      shell: bash         
      run: docker build -t ${{env.imageRepository}}:${{env.version}} -f ./src/Kibana.Alerts/Dockerfile ./src/Kibana.Alerts/  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: hub.docker.com
        username: ${{ secrets.DOCKERHUB_TOKEN }}
        password: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: "docker - tag and push"
      run: |
          # docker pull ${{env.imageRepository}}:build-${{env.version}}-amd64
          # docker manifest create ${{env.imageRepository}}:${{env.version}} ${{env.imageRepository}}:build-${{env.version}}-amd64
          # docker manifest create ${{env.imageRepository}}:latest ${{env.imageRepository}}:build-${{env.version}}-amd64
          # docker manifest push ${{env.imageRepository}}:${{env.version}}
          # docker manifest push ${{env.imageRepository}}:latest
          docker tag ${{env.imageRepository}}:${{env.version}} ${{env.imageRepository}}:latest
          docker push --all-tags ${{env.imageRepository}}:${{env.version}}
