name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        type: string
        required: true 
env:
  DOTNET_NOLOGO: true
  imageRepository: "cjoergensendk/thrifty-elastic-alerting"

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image
      shell: bash         
      run: | 
          docker build -t ${{env.imageRepository}}:${{ github.event.inputs.version }} -f ./src/Worker/Dockerfile ./src/
          docker tag ${{env.imageRepository}}:${{ github.event.inputs.version }} ${{env.imageRepository}}:latest
          docker push --all-tags ${{env.imageRepository}}

  create-github-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        generate_release_notes: true
        files: |
          samples/kubernetes/thrifty.yaml